#pragma once

#include <cstddef>
#include <iostream>

#include "seal/seal.h"
#include "sealnet/batchencoder_wrapper.h"
#include "sealnet/biguint_wrapper.h"
#include "sealnet/ciphertext_wrapper.h"
#include "sealnet/ckksencoder_wrapper.h"
#include "sealnet/contextdata_wrapper.h"
#include "sealnet/decryptor_wrapper.h"
#include "sealnet/defines.h"
#include "sealnet/encryptionparameterqualifiers_wrapper.h"
#include "sealnet/encryptionparameters_wrapper.h"
#include "sealnet/encryptor_wrapper.h"
#include "sealnet/evaluator_wrapper.h"
#include "sealnet/galoiskeys_wrapper.h"
#include "sealnet/intencoder_wrapper.h"
#include "sealnet/keygenerator_wrapper.h"
#include "sealnet/kswitchkeys_wrapper.h"
#include "sealnet/memorymanager_wrapper.h"
#include "sealnet/memorypoolhandle_wrapper.h"
#include "sealnet/modulus_wrapper.h"
#include "sealnet/plaintext_wrapper.h"
#include "sealnet/publickey_wrapper.h"
#include "sealnet/relinkeys_wrapper.h"
#include "sealnet/sealcontext_wrapper.h"
#include "sealnet/secretkey_wrapper.h"
#include "sealnet/serialization_wrapper.h"
#include "sealnet/smallmodulus_wrapper.h"
#include "sealnet/stdafx.h"
// #include "sealnet/targetver.h"
#include "sealnet/utilities.h"
#include "sealnet/valcheck_wrapper.h"